<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <title>TrackFlow - Transaction Report - {{ $user->name }}</title>
    <link rel="icon" type="image/png" href="{{ asset('trackflow-main/fav-icon.png') }}">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4F46E5;
            padding-bottom: 20px;
            position: relative;
        }

        .header-logo {
            position: absolute;
            top: 0;
            right: 0;
            width: 80px;
            height: auto;
        }

        .header h1 {
            color: #4F46E5;
            margin: 0 0 10px 0;
        }

        .header p {
            margin: 5px 0;
            color: #666;
        }

        .info-section {
            margin-bottom: 20px;
            background: #f9fafb;
            padding: 15px;
            border-radius: 8px;
        }

        .info-section p {
            margin: 5px 0;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }

        th {
            background-color: #4F46E5;
            color: white;
            padding: 12px;
            text-align: left;
            font-weight: 600;
        }

        td {
            padding: 10px 12px;
            border-bottom: 1px solid #e5e7eb;
        }

        tr:nth-child(even) {
            background-color: #f9fafb;
        }

        tr:hover {
            background-color: #f3f4f6;
        }

        .type-credit {
            color: #10b981;
            font-weight: 600;
        }

        .type-debit {
            color: #ef4444;
            font-weight: 600;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #e5e7eb;
            padding-top: 20px;
        }

        @media print {
            body {
                margin: 0;
            }

            .no-print {
                display: none;
            }
        }
    </style>
</head>

<body>
    <div class="header">
        <img src="{{ asset('trackflow-main/logo.png') }}" alt="TrackFlow Logo" class="header-logo">
        <h1>TrackFlow Financial Report</h1>
        <p><strong>{{ $user->name }}</strong></p>
        <p>{{ $user->email }}</p>
        <p>Generated on: {{ $generatedDate }}</p>
    </div>

    <div class="info-section">
        <p><strong>Report Type:</strong> All Transactions</p>
        <p><strong>Total Transactions:</strong> {{ $transactions->count() }}</p>
        <p><strong>Currency:</strong> {{ $currencySymbol }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Date</th>
                <th>Description</th>
                <th>Type</th>
                <th>Amount</th>
                <th>Category</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse($transactions as $transaction)
                <tr>
                    <td>{{ $transaction['Date'] }}</td>
                    <td>{{ $transaction['Description'] }}</td>
                    <td class="{{ strtolower($transaction['Type']) === 'credit' ? 'type-credit' : 'type-debit' }}">
                        {{ $transaction['Type'] }}
                    </td>
                    <td>{{ $transaction['Amount'] }}</td>
                    <td>{{ $transaction['Category'] }}</td>
                    <td>{{ $transaction['Status'] }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="6" style="text-align: center; padding: 20px; color: #999;">
                        No transactions found
                    </td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>This report was generated by TrackFlow - Personal Finance Management System</p>
        <p>&copy; {{ date('Y') }} TrackFlow. All rights reserved.</p>
    </div>

    <div class="no-print" style="margin-top: 30px; text-align: center;">
        <button onclick="window.print()"
            style="padding: 10px 20px; background: #4F46E5; color: white; border: none; border-radius: 8px; cursor: pointer; font-size: 16px;">
            Print / Save as PDF
        </button>
    </div>
</body>

</html>